export interface IPostData {
    id: number;
    title: string;
    date: string;
    description: string;
    content: string;
}

// Reusable type for creating or editing a post where id and date
// are generated by the server. Use this instead of repeating Omit<>.
export type NewPostPayload = Omit<IPostData, 'id' | 'date'>;